name: CI
# pipeline doc see: `doc/ci-pipelines.md`

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  windows-build:
    strategy:
      fail-fast: false
      matrix:
        os: [windows-latest]
        libtype: [shared]
    runs-on: ${{matrix.os}}
    name: Win-${{matrix.libtype}}
    steps:
      # Setup build env
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: '3.x'
      - name: Install Meson+Ninja
        run: |
          python -m pip install --upgrade pip
          pip install meson ninja
      - name: Setup MSVC
        uses: ilammy/msvc-dev-cmd@v1

      - name: Build
        shell: cmd
        run: |
          meson setup builddir --buildtype=debug --default-library=${{matrix.libtype}}
          ninja -C builddir --verbose

      # TODO: Add test
      # - name: Run test
      #   run: meson test -C builddir --verbose

      - name: Upload artifacts
        uses: actions/upload-artifact@v2
        with:
          name: ${{ matrix.config.name }}
          path: |
            builddir/meson-logs/*.log
            builddir/meson-out/*.exe
            builddir/meson-out/*.pdb
            builddir/meson-out/libui.*
